with case_dimension as (
    SELECT 
        COLUMN_NAME
    FROM 
         INFORMATION_SCHEMA.COLUMNS
    WHERE 
        TABLE_SCHEMA = 'JABAR_DATA_SCHEMA' AND TABLE_NAME = 'JABAR_COVID_KAB'
    AND 
        COLUMN_NAME IN ('SUSPECT_DISCARDED', 'PROBABLE_DISCARDED', 'CLOSECONTACT_DISCARDED','PROBABLE_MENINGGAL', 'PROBABLE_DIISOLASI', 'CLOSECONTACT_MENINGGAL', 'CLOSECONTACT_DIKARANTINA', 'CONFIRMATION_MENINGGAL', 'CONFIRMATION_SEMBUH', 'SUSPECT_MENINGGAL', 'SUSPECT_DIISOLASI')
)
SELECT
    row_number() OVER(ORDER BY COLUMN_NAME) as id,
    MAX(SPLIT_PART(COLUMN_NAME, '_', 1)) as status_name,
    MAX(SPLIT_PART(COLUMN_NAME, '_', 2)) as status_detail,
    MAX(COLUMN_NAME) as status
FROM
    case_dimension
GROUP BY
    COLUMN_NAME